### ISSUE TITLE
Builder output with quantization enabled yields incorrect negative scales.

### ISSUE THREAD

**Issue by aendk** [microsoft/onnxruntime-genai#1051]
#**Describe the bug**
Quantization scales are defined to _always_ be positive in the [onnx documentation](https://iot-robotics.github.io/ONNXRuntime/docs/performance/quantization.html). 
Creating a qdq-enabled onnx-representation using the `builder.py` lead to plenty of negative scales, contrary to what is stated in the documentation.
It also causes exceptions in various execution providers.

1. Download a model from hugginface, in our case `Phi-3.5-mini-instruct`.
2. Create a quantized onnx-represenation from it, with a call similar to this:
```
python builder.py -m /path/to/downloaded/model -e cuda -p int4 -o /desired/path/to/result --extra_options use_qdq=1
```
3. Open this new onnx-representation using `netron`
4. Click on a random `DequantizeLinear` node.
5. In the opened sidebar, find `Inputs`, and there `x_scale`. Click on the associated `+`-sign on the right.
6. See that there are many negative values.

**Expected behavior**
In Step 6, only 0 or positive values should be visible.

**Desktop (please complete the following information):**
ubuntu

**Screenshots** 
![Image](https://github.com/user-attachments/assets/ff43dee8-19fe-4ade-aecf-bcf845db7188)

**Comment by kunal-vaishnavi** [comment]
When quantizing to INT4 precision, the model builder assumes that the scales are symmetric. When `is_symmetric = True`, the scales can be positive or negative. If `is_symmetric = False`, the scales will be non-negative.

https://github.com/microsoft/onnxruntime-genai/blob/2f2686feea75a8f6d56c09088adc1b051f9224d4/src/python/py/models/builder.py#L463-L474

This can be fixed by adding the ability to set `is_symmetric` using the `--extra_options`. Here's [the PR](https://github.com/microsoft/onnxruntime-genai/pull/1053) to enable this.
