### ISSUE TITLE
Ort::InitApi() is only called after Generator related code is invoked

### ISSUE THREAD

**Issue by skyline75489** [microsoft/onnxruntime-genai#566]
`OrtEnv` is created at

https://github.com/microsoft/onnxruntime-genai/blob/a6bec83bf02667f6a9c6aa6340842f46e001578c/src/generators.cpp#L14

Calling other APIs before initializing `OrtEnv`:

```python
import onnxruntime_genai as ort_genai
ort_genai.get_current_gpu_device_id()
```

Will fail:

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
onnxruntime_genai.onnxruntime_genai.OrtException: /onnxruntime_src/include/onnxruntime/core/common/logging/logging.h:320 static const onnxruntime::logging::Logger& onnxruntime::logging::LoggingManager::DefaultLogger() Attempt to use DefaultLogger but none has been registered.
```

**Comment by baijumeswani** [comment]
This should not happen. The static global variables should be created when the module is imported.

```
import onnxruntime_genai as ort_genai
```

should create the static variables inside ort-genai.

So, that should never happen. I just tried it on my linux machine and didn't see any error reported. Not sure if something changed since this issue was created and now. I will close this issue.
