### ISSUE TITLE
No support for multiple image while using Phi-3-vision (Inference)

### ISSUE THREAD

**Issue by mohamedlotfy50** [microsoft/onnxruntime-genai#587]
I am currently using `microsoft/Phi-3-vision-128k-instruct-onnx-cpu` and trying to add multiple images but it crashes every time which an error message tells there is no support for python object `list`:
```python
RuntimeError: Unable to cast Python instance to C++ type (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
PS C:\Users\hxhy4251\OneDrive - orange.com\Bureau\smart_menu\step_01_area_selection_snip_tool> 
```
code:
![image](https://github.com/microsoft/onnxruntime-genai/assets/51348724/b6c4184c-98c0-4eec-934f-060d0d63fd4b)

**Comment by baijumeswani** [comment]
We do not have support for multiple images per prompt as of now. Adding multiple image per prompt support requires change to the ort-genai code, API as well as the phi3-vision onnx models.
We have added this item to the planning doc for 0.4.0 and will sync internally on whether we can prioritize this above other feature requests.

I'll close this issue since it has [been raised earlier as well](https://github.com/microsoft/onnxruntime-genai/issues/562).
