### ISSUE TITLE
Onnxruntime-genai with Phi3 produces nonsense on LicheePi4A ( RISCV- XuanTie C910 )

### ISSUE THREAD

**Issue by staberas** [microsoft/onnxruntime-genai#594]
System: LicheePi4A , XuanTie C910/TH1520 
OS: Linux Debian 
Model used phi3 - cpu and mobile - acc level 4 (from huggingface)
Python3.11 - onnxruntime version 1.19.0 -  onnxruntime_genai version 0.4.0-dev

![image](https://github.com/microsoft/onnxruntime-genai/assets/2744235/5b0b6ff2-50e7-4914-983f-dcc857384588)

**Comment by kunal-vaishnavi** [comment]
Since you are using ONNX Runtime v1.19.0 and ONNX Runtime GenAI v0.4.0-dev, it appears you are building both from source. I built ONNX Runtime from source on commit [`05032e5`](https://github.com/microsoft/onnxruntime/tree/05032e5e5fff4d55b0178f27fba42161c255f3f5) and ONNX Runtime GenAI from source on commit [`8608d13`](https://github.com/microsoft/onnxruntime-genai/tree/8608d1317d9a97101adb3f4fea7889eb348445fb). Using those builds, I was able to run your example successfully.

```
$ python3 phi3-qa.py -m /path/to/Phi-3-mini-128k-instruct-onnx/cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4
Input: Tell me a joke about Generative AI

Output:  Why don't Generative AI's go on vacation?

Because they can't "un-compute" their work!
```

Can you re-build both ONNX Runtime and ONNX Runtime GenAI using the latest commits on the main branches and try again?

**Comment by staberas** [comment]
will try , will take some hours since i had to edit alot of files to build it on riscv

**Comment by staberas** [comment]
nop still doesnt work, it took me time to figure out how i get commit and a full day rebuilding and redoing all the build fixes 

onnxruntime -  dc545d366d 
gen-ai  - e7c4e9e

**Comment by kunal-vaishnavi** [comment]
Can you share the changes that you are making to build with your system?

**Comment by staberas** [comment]
`  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
    set(genai_target_platform "x64")
  elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^riscv64.*")
    set(genai_target_platform "riscv64")
  else()
    message(FATAL_ERROR "Unsupported architecture. CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
  endif() `
  at  **_cmake/global_variables.cmake_**

and the riscv toolchain cmake file, after that i just compile it

**Comment by staberas** [comment]
I give up, its likely have to do with riscv vector intrinsics, it only compiles on gcc-13 and not gcc-14 but that's just speculation on my part without anyone to help.  Closing issue.
