### ISSUE TITLE
Convert Llama-3-awq To Llama-3-awq-onnx

### ISSUE THREAD

**Issue by Toan-it-mta** [microsoft/onnxruntime-genai#677]
### Issue: Error Converting Quantized Llama-3-awq Model to ONNX

Hello,

I used AutoAWQ to quantize the Llama-3 model and obtained Llama-3-awq. I then attempted to convert the model to Llama-3-awq-onnx using the following command:

```bash
python -m onnxruntime_genai.models.builder -i /data2/cmdir/home/ioit104/aiavn/llama/models/llama3-awq -o /data2/cmdir/home/ioit104/aiavn/llama/models/llama3-awq-onnx -p int4 -e cuda
```
However, I encountered an error. Below are the logs:
```logs
/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:950: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:469: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
You have loaded an AWQ model on CPU and have a CUDA device available, make sure to set your model on a GPU device in order to run your model.
`low_cpu_mem_usage` was None, now set to True since model is quantized.
2024-07-04 20:35:26,791 datasets [INFO] - PyTorch version 2.3.0+cu121 available.
Valid precision + execution provider combinations are: FP32 CPU, FP32 CUDA, FP16 CUDA, FP16 DML, INT4 CPU, INT4 CUDA, INT4 DML
Extra options: {}
GroupQueryAttention (GQA) is used in this model.
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  7.97it/s]
Traceback (most recent call last):
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 2376, in <module>
    create_model(args.model_name, args.input, args.output, args.precision, args.execution_provider, args.cache_dir, **extra_options)
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 2269, in create_model
    onnx_model.make_model(input_path)
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 1457, in make_model
    self.make_layer(self.layer_id, module)
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 1413, in make_layer
    self.make_attention(layer_id, layer.self_attn, self.layernorm_attrs["output_0"])
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 1148, in make_attention
    self.make_packed_matmul(attention.q_proj.weight.detach().numpy(), attention.k_proj.weight.detach().numpy(), attention.v_proj.weight.detach().numpy(), qkv_matmul_name, root_input)
  File "/data2/cmdir/home/ioit104/.conda/envs/python310cu121/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'WQLinear_GEMM' object has no attribute 'weight'. Did you mean: 'qweight'?
Reading embedding layer
Reading decoder layer 0
```
I am grateful for any help

**Comment by kunal-vaishnavi** [comment]
Based on your logs, it appears that the AWQ-quantized model was loaded with Hugging Face's `AutoModelForCausalLM` rather than ONNX Runtime GenAI's `QuantModel`. This means that the quantization case in the below logic was not entered.

https://github.com/microsoft/onnxruntime-genai/blob/4b0dd43064287dfbd6f13f16593d36b5525c0cdc/src/python/py/models/builder.py#L1547-L1568

This means that `self.quant_type = None`. For `self.quant_type = None`, either the `quantization_config` entry must not be present in your `config.json` file or `quant_method` is not an entry within the `quantization_config` dictionary.

https://github.com/microsoft/onnxruntime-genai/blob/4b0dd43064287dfbd6f13f16593d36b5525c0cdc/src/python/py/models/builder.py#L41

AutoAWQ should add a `quantization_config` entry in `config.json` for you. Do you see a `quantization_config` entry in `config.json` after using AutoAWQ? Here are some examples of how that entry looks in various AWQ-quantized PyTorch models in Hugging Face.

- [casperhansen/llama-3-70b-instruct-awq](https://huggingface.co/casperhansen/llama-3-70b-instruct-awq/blob/e578178ea893ca5e3326afd15da5aefa37e84d69/config.json#L20)
- [mayflowergmbh/Llama-3-SauerkrautLM-8b-Instruct-AWQ](https://huggingface.co/mayflowergmbh/Llama-3-SauerkrautLM-8b-Instruct-AWQ/blob/a1247003359ad44a2331e0d8653c4c3257b4d768/config.json#L20)
- [elyza/Llama-3-ELYZA-JP-8B-AWQ](https://huggingface.co/elyza/Llama-3-ELYZA-JP-8B-AWQ/blob/85c3670a70d1e53bb4faa3f01c3ac2878f4a3fcd/config.json#L21)
- [Infinirc/Infinirc-Llama3-8B-4bit-AWQ-GEMM-Beta](https://huggingface.co/Infinirc/Infinirc-Llama3-8B-4bit-AWQ-GEMM-Beta/blob/ba9d28a332c1c8b1a340d45fad0db09680442c95/config.json#L21)
- [amir-ma71/Dorna-Llama3-8B-Instruct-AWQ](https://huggingface.co/amir-ma71/Dorna-Llama3-8B-Instruct-AWQ/blob/9fac86557fa3c4706529168f55196235c43c1776/config.json#L21)

If the `quantization_config` entry is not present or the `quant_method` entry is missing from the `quantization_config` dictionary, you can add it manually and try running your command again.

**Comment by Toan-it-mta** [comment]
I checked the config.json file and it matches the sample models you provided. Below is my configuration file. 
```
{
  "_name_or_path": "/data2/cmdir/home/ioit104/aiavn/llama/models/llama3",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "eos_token_id": 128001,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "pretraining_tp": 1,
  "quantization_config": {
    "bits": 4,
    "group_size": 128,
    "modules_to_not_convert": null,
    "quant_method": "awq",
    "version": "gemm",
    "zero_point": true
  },
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 500000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.42.3",
  "use_cache": true,
  "vocab_size": 128256
}
```
I solved the problem by running the command instead of the above:
```
# From source:
python3 builder.py -i path_to_local_folder_on_disk -o path_to_output_folder -p int4 -e execution_provider -c cache_dir_to_store_temp_files

```
