### ISSUE TITLE
Library affecting other onnx runtimes

### ISSUE THREAD

**Issue by janjanusek** [microsoft/onnxruntime-genai#681]
Hello, I would like to inform you about very ugly bug which I opened at sherpa-onnx but the source of the problem comes from this library. Once I installed this and used PHI3 in my project it started to affect other sherpa-onnx library.

Here is the problem description: https://github.com/k2-fsa/sherpa-onnx/issues/1081

It's related to .NET package.

**Comment by baijumeswani** [comment]
As of now, the [Microsoft.ML.OnnxRuntimeGenAI](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI) package has the onnxruntime.dll shared library embedded inside it.

Since at any given time only one copy of onnxruntime.dll can be loaded, the version of onnxruntime.dll that get's loaded first will be the one that is used by all applications needing it.

This can cause problems as you have encountered. We are planning on moving away from this approach and instead are planning to take a dependency on the onnxruntime.dll packaged inside [Microsoft.ML.OnnxRuntime](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime). That way, all applications can have a single onnxruntime.dll that they can depend on.

The problem you encountered is because the version of onnxruntime.dll packaged inside Microsoft.ML.OnnxRuntimeGenAI (branched off of 1.18.1 onnxruntime) is not compatible with the version of the referenced package (sherpa-onnx). It would be great if sherpa-onnx is also able to move away from embedding the onnxruntime.dll inside it (if possible).

**Comment by baijumeswani** [comment]
Closing this since there isn't much we can do to address the referenced error. For the next release, we will be avoiding bundling onnxruntime shared libs with the onnxruntime-genai packages.
