### ISSUE TITLE
Help needed to export Phi3v in ONNX

### ISSUE THREAD

**Issue by ladanisavan** [microsoft/onnxruntime-genai#685]
Hi there,

I'm seeking guidance on exporting a custom fine-tuned Phi-3 Vision model to ONNX. I've followed the ONNX build model guide from [this link](https://onnxruntime.ai/docs/genai/howto/build-model.html).

The build command I used was:
`python3 -m onnxruntime_genai.models.builder -i ep_2_grad_32_lr_3e-5/ -o onnx_output/ -p int4 -e cuda --extra_options int4_block_size=32 int4_accuracy_level=4`

The build process was successful and generated the following files:

- genai_config.json
- model.onnx
- model.onnx.data
- special_tokens_map.json
- tokenizer.json
- tokenizer_config.json

However, the number of files generated doesn't match the file count in the official HF repo for ONNX `microsoft/Phi-3-vision-128k-instruct-onnx-cuda`

Files highlighted in red below are missing:
<img width="1196" alt="Screenshot 2024-07-05 at 5 56 00 PM" src="https://github.com/microsoft/Phi-3CookBook/assets/14819841/dba377ac-ed7c-4036-b268-c4df8a08a4db">

Additionally, while loading the model using ONNX Runtime, the following error occurs:
`OrtException: Load model from onnx_output failed: Protobuf parsing failed.`

I have also noticed that sections for "embedding" and "vision" are missing from the `genai_config.json`

Can someone help me identify if I'm missing anything? Thanks

**Comment by kunal-vaishnavi** [comment]
The Phi-3 vision ONNX models are created as follows.

- The vision component (`phi-3-v-128k-instruct-vision.onnx`) is created using `torch.onnx.export` with some modifications to the original PyTorch source code.
- The text embedding component (`phi-3-v-128k-instruct-text-embedding.onnx`) is created using the ONNX helper APIs.
- The text component (`phi-3-v-128k-instruct-text.onnx`) is created using the model builder with `--extra_options exclude_embeds=true` enabled. The model builder prints a warning that only the text component is created.
https://github.com/microsoft/onnxruntime-genai/blob/00ceb80e1984c408459dfabe92a5b4eb97318578/src/python/py/models/builder.py#L2387-L2388
- The `genai_config.json` is created manually.

I can open-source the scripts and workflows used to create these ONNX models and run them with ONNX Runtime GenAI.

**Comment by 2U1** [comment]
@kunal-vaishnavi If you open-source it, I would really appreciate it!

**Comment by ladanisavan** [comment]
@kunal-vaishnavi open-source scripts would be really helpful to the Phi community.

**Comment by kunal-vaishnavi** [comment]
I have uploaded the necessary files in each of the Hugging Face repos and created [this PR](https://github.com/microsoft/onnxruntime-genai/pull/705) to show how to use them.

- [`microsoft/Phi-3-vision-128k-instruct-onnx-cpu`](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx-cpu/tree/main/onnx)
- [`microsoft/Phi-3-vision-128k-instruct-onnx-cuda`](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx-cuda/tree/main/onnx)
- [`microsoft/Phi-3-vision-128k-instruct-onnx-directml`](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx-directml/tree/main/onnx)

**Comment by tgalery** [comment]
Quick question, would the same guide work for Phi3.5 vision model family ?

**Comment by kunal-vaishnavi** [comment]
Yes, but the `num_crops` value in `processor_config.json` [here](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx-cpu/blob/6743d1f4962c706a472e8f922e20bd59c06fb0b7/cpu-int4-rtn-block-32-acc-level-4/processor_config.json#L28) needs to be set to 4 for Phi-3.5 vision as [the value has changed](https://huggingface.co/microsoft/Phi-3.5-vision-instruct/blob/c69b58c1be8dfda05972fdf495be3511e3b0f61f/preprocessor_config.json#L18).

Please note that this guide only works for a single image, however. We have re-designed the ONNX models so that there is multi-image support for both Phi-3 vision and Phi-3.5 vision. As mentioned [here](https://github.com/microsoft/onnxruntime-genai/issues/849#issuecomment-2327045791), the new ONNX models are undergoing [Microsoft's Responsible AI evaluations](https://www.microsoft.com/en-us/ai/principles-and-approach) before they can be published officially.

The changes needed within ONNX Runtime GenAI for the new ONNX models have already been merged in [this PR](https://github.com/microsoft/onnxruntime-genai/pull/882). A revised guide as well as a new ONNX Runtime GenAI stable release will be published together to support this work.
