### ISSUE TITLE
[Build] genai_config

### ISSUE THREAD

**Issue by Dave86ch** [microsoft/onnxruntime-genai#754]
### Describe the issue

Hello everyone,

I'm trying to build a mobile app using the HuggingFace model SmolLM-135M. I would like to use the model.onnx file, but I'm having a hard time retrieving the necessary information to build it. I am trying a simple script, but it seems like I am missing the genai_config. 

Can someone direct me to where I can get information on how to use this model?

### Target platform

Android-python

### Build script

import onnxruntime_genai as og

prompt = '''def print_prime(n):
    """
    Print all primes between 1 and n
    """'''

model = og.Model('onnx-model-runner/model')

tokenizer = og.Tokenizer(model)

tokens = tokenizer.encode(prompt)

params = og.GeneratorParams(model)
params.set_search_options({"max_length": 200})
params.input_ids = tokens

output_tokens = model.generate(params)[0]

text = tokenizer.decode(output_tokens)

print(text)

prompts = [
    "This is a test.",
    "Rats are awesome pets!",
    "The quick brown fox jumps over the lazy dog.",
]

inputs = tokenizer.encode_batch(prompts)

params = og.GeneratorParams(model)
params.input_ids = tokens

outputs = model.generate(params)[0]

text = tokenizer.decode(output_tokens)

print(text)

### Error / output

Traceback (most recent call last):
  File "/home/davesoma/llms/Onnx/onnx-model-runner/Main3.py", line 8, in <module>
    model=og.Model(f'onnx-model-runner/model')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error opening onnx-model-runner/model/genai_config.json

**Comment by kunal-vaishnavi** [comment]
The uploaded ONNX model for `HuggingFaceTB/SmolLM-135M` that is available [here](https://huggingface.co/HuggingFaceTB/SmolLM-135M/blob/main/onnx/model.onnx) has matching input and output names. However, the ONNX model appears to be unoptimized.

Can you try using [ONNX Runtime GenAI's model builder](https://github.com/microsoft/onnxruntime-genai/blob/main/src/python/py/models/README.md) to generate the optimized and/or quantized ONNX model? The model builder will generate everything you need for ONNX Runtime GenAI including the `genai_config.json` file.

Here is an example command for FP32 CPU.
```bash
$ python -m onnxruntime_genai.models.builder -m HuggingFaceTB/SmolLM-135M -o ./SmolLM_135M_fp32 -p fp32 -e cpu -c ./cache_dir
```

Here's an example command for INT4 CPU since you would like to run the ONNX model on a mobile device.
```bash
$ python -m onnxruntime_genai.models.builder -m HuggingFaceTB/SmolLM-135M -o ./SmolLM_135M_int4 -p int4 -e cpu -c ./cache_dir
```

**Comment by Dave86ch** [comment]
Thank you, it works.

Now, I have trouble running the model:
```
import onnxruntime_genai as og

model = og.Model('/home/davesoma/llms/Onnx/onnx-model-runner/src/python/QwenOnnxMobile')

tokenizer = og.Tokenizer(model)

prompt = "what is the meaning of life?"

tokens = tokenizer.encode(prompt)

params = og.GeneratorParams(model)
params.input_ids = tokens

try:
    output_tokens = model.generate(params)[0]
    generated_text = tokenizer.decode(output_tokens)
  
    
    print(response)
except Exception as e:
    print("Error during generation:", str(e))
```
I encountered the following error:

```
RuntimeError: Unsupported model_type in config.json: qwen2
```

any suggestion? thank you

**Comment by kunal-vaishnavi** [comment]
Support for Qwen was recently added in [this PR](https://github.com/microsoft/onnxruntime-genai/pull/739). To run Qwen, you will need to [build ONNX Runtime GenAI from source](https://onnxruntime.ai/docs/genai/howto/build-from-source.html) for now. We are planning to publish an RC package soon that will include these changes. Once published, you can run Qwen by simply upgrading to the RC package instead of needing to build from source.

**Comment by Dave86ch** [comment]
> Support for Qwen was recently added in [this PR](https://github.com/microsoft/onnxruntime-genai/pull/739). To run Qwen, you will need to [build ONNX Runtime GenAI from source](https://onnxruntime.ai/docs/genai/howto/build-from-source.html) for now. We are planning to publish an RC package soon that will include these changes. Once published, you can run Qwen by simply upgrading to the RC package instead of needing to build from source.

Sorry to bother you, but do you have any suggestions for using Qwen as a local model in an Android app, given the absence of ONNX support?

**Comment by kunal-vaishnavi** [comment]
The RC packages will be published this week. If all goes well with validation, the RC package will be published tomorrow. You can then upgrade to the RC package to have support for Qwen.

**Comment by kunal-vaishnavi** [comment]
ONNX Runtime GenAI v0.4.0 is now released on PyPI and NuGet. You can now upgrade to run your Qwen model.

**Comment by drlima** [comment]
Hey, folks!

I am reviving this topic as I follow it to run the model on Android.
Right now, after quantization with int4 and CPU, the outputs I get don't follow any instructions; they just give me random responses that are out of context.

Have any of you guys noticed a similar behavior? 
CC-ing you only because it's an old topic: @Dave86ch, @wangyems, and @kunal-vaishnavi
