### ISSUE TITLE
Phi3 mini 128k instruct conversion to onnx yields model not deployable to AWS Sagemaker

### ISSUE THREAD

**Issue by nimishbongale** [microsoft/onnxruntime-genai#915]
**Describe the bug**

The model card here mentions that the phi3-mini-128k-instruct-onnx model is directly deployable to sagemaker runtime using `get_huggingface_llm_image_uri("huggingface",version="2.2.0")` as image uri. However, on deploying, sagemaker fails to recognize the onnx model and attempts to find pytorch weights, thus failing the builds. 

I'm loading in the model to `/opt/ml/model` folder using s3_uri, and then mentioning the same path as `HF_MODEL_ID`.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/2da2dd45-112d-4fa3-8839-a7a8cc4a264b">

**To Reproduce**
1. Try deploying onnx model to AWS Sagemaker using latest version of sagemaker==2.32.1

**Expected behavior**
Model should get deployed seamlessly, just like how phi-3-mini-128k-instruct (non-onnx) does.

**Screenshots**

<img width="913" alt="image" src="https://github.com/user-attachments/assets/02350131-e971-4be9-b2b3-6856343a123f">

**Desktop (please complete the following information):**
- AWS Sagemaker Runtime

**Comment by nimishbongale** [comment]
<img width="750" alt="image" src="https://github.com/user-attachments/assets/b7c3633f-2efe-49c4-a1a1-ff9400c1dc3a">

**Comment by kunal-vaishnavi** [comment]
The AWS SageMaker instructions are auto-generated by Hugging Face on the model cards. Hugging Face assumes that each repo contains PyTorch models, which is why you are getting a `FileNotFoundError` in this repo containing only ONNX models.

For deploying ONNX models to AWS SageMaker, there are some online guides that you can try to follow. [Here](https://awstip.com/deploy-a-transformer-onnx-model-to-sagemaker-510ab52666e4) is an example one that you can try to follow starting from the "Create an Inference Handler" section. [Here](https://aws.amazon.com/blogs/machine-learning/host-ml-models-on-amazon-sagemaker-using-triton-onnx-models/) is an example with Triton Inference Server.

You can also use [Azure ML](https://learn.microsoft.com/en-us/azure/machine-learning/concept-onnx?view=azureml-api-2) to deploy ONNX models. [Here](https://onnxruntime.ai/docs/tutorials/azureml.html) is a guide you can follow. For a more detailed example, you can look at [this guide](https://techcommunity.microsoft.com/t5/educator-developer-blog/the-full-guide-to-packaging-and-deploying-ml-models-to/ba-p/3855628).

Please note that there are multiple ONNX models uploaded in this repo. You can follow [this example](https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx/discussions/1#662ff0e991587703a6866524) to pick one of the ONNX models to load using Hugging Face's Optimum. Then you can use Optimum to manage the generation loop with `model.generate(...)` in your inference script. Optimum will use ONNX Runtime under the hood and manage preparing the inputs for you.

**Comment by nimishbongale** [comment]
Thanks for the clarification @kunal-vaishnavi 

I'm unfortunately bound to using AWS Sagemaker for my deployments, so I'll have to proceed with a custom inference script using Optimum like you mentioned.

Are there plans to include optimum or onnxruntime-genai support in the next tgi images within sagemaker?

**Comment by kunal-vaishnavi** [comment]
> I'm unfortunately bound to using AWS Sagemaker for my deployments, so I'll have to proceed with a custom inference script using Optimum like you mentioned.

If you create your own image on top of existing TGI images, you can install and use ONNX Runtime GenAI directly instead of Optimum for the best performance in your custom inference script. [Here](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi3-qa.py) is an example inference script that you can modify for AWS SageMaker.

> Are there plans to include optimum or onnxruntime-genai support in the next tgi images within sagemaker?

This is a good idea. According to [this issue](https://github.com/huggingface/text-generation-inference/issues/1873), Hugging Face's TGI currently doesn't support ONNX models. We will discuss internally to see if adding ONNX Runtime GenAI is possible.

**Comment by kunal-vaishnavi** [comment]
> I'm unfortunately bound to using AWS Sagemaker for my deployments, so I'll have to proceed with a custom inference script using Optimum like you mentioned.

If you create your own image on top of existing TGI images, you can install and use ONNX Runtime GenAI directly instead of Optimum for the best performance in your custom inference script. [Here](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi3-qa.py) is an example inference script that you can modify for AWS SageMaker.

> Are there plans to include optimum or onnxruntime-genai support in the next tgi images within sagemaker?

According to [this issue](https://github.com/huggingface/text-generation-inference/issues/1873), Hugging Face's TGI currently doesn't support ONNX models. We will discuss internally to see if adding ONNX Runtime GenAI is possible.

**Comment by nimishbongale** [comment]
Thanks once again

I've actually used the `model-generate.py` file for the deployment and that has gone smoothly. However a couple of observations:

1. The phi3 model prior to conversion supports an environment variable `"return_full_text":False`, which stops the model from echoing the user prompt. The onnxruntime-genai library however does not allow for setting this variable later on. 
2. At times the qa model using the token streaming is faster than just the direct generation, but that ideally shouldn't be the case.

Do let me know if you have any pointers in this regards, appreciate the help!

**Comment by kunal-vaishnavi** [comment]
> The phi3 model prior to conversion supports an environment variable "return_full_text":False, which stops the model from echoing the user prompt. The onnxruntime-genai library however does not allow for setting this variable later on.

There isn't an environment variable to set this in ONNX Runtime GenAI. But you can filter out the user prompt with some additional logic in the inference script.

The input tokens are set here.
https://github.com/microsoft/onnxruntime-genai/blob/bcf55a6dc563bc8b356128b47504d59a21c5ef2f/examples/python/model-generate.py#L40

After the output tokens have been generated, you can go through them to remove the first $N_b$ tokens per batch entry where $N_b$ is the length of the input tokens at batch entry $b$.
https://github.com/microsoft/onnxruntime-genai/blob/bcf55a6dc563bc8b356128b47504d59a21c5ef2f/examples/python/model-generate.py#L45

Here is some pseudocode for a naive implementation.
```python
output_tokens_without_user_prompt = []
for b in range(len(output_tokens)):
    N_b = len(input_tokens[b])
    without_user_prompt = output_tokens[b][N_b : ]
    output_tokens_without_user_prompt.append(without_user_prompt)
```

Then, when you print the generated tokens, the user prompt will not be re-printed.
```python
for i in range(len(prompts)): 
    print(f'Prompt #{i}: {prompts[i]}') 
    print() 
    print(tokenizer.decode(output_tokens_without_user_prompt[i])) 
    print() 
```

Please note that this logic may need to be modified to handle padding in the input tokens when calculating $N_b$.

> At times the qa type (using the token streaming) is faster than just the direct generation, but that ideally shouldn't be the case.

We are able to repro this and we will look into it.
