### ISSUE TITLE
Build from source on Windows with default ONNX Runtime fails to run unit tests from visual studio

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime-genai#935]
**Describe the bug**
follow instructions at
https://onnxruntime.ai/docs/genai/howto/build-from-source.html
the build fails to run unit tests

**To Reproduce**
1.
git clone https://github.com/microsoft/onnxruntime-genai
cd onnxruntime-genai

2.
curl -L https://github.com/microsoft/onnxruntime/releases/download/v1.19.2/onnxruntime-win-x64-1.19.2.zip -o onnxruntime-win-x64-1.19.2.zip
tar xvf onnxruntime-win-x64-1.19.2.zip
move onnxruntime-win-x64-1.19.2 ort 

3.
python build.py --config Release

4. open Generator.sln with vs studio, set unit_tests as the startup program and run.
got "The given version [19] is not supported, only version 1 to 10 is supported in this build."

 
**Expected behavior**
The test shall run and pass

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baijumeswani** [comment]
@liqunfu could you try copying the onnxruntime dll to the same directory as the sln file or the unit_test.exe file?

**Comment by liqunfu** [comment]
Thanks @baijumeswani, it works if I copy over onnxruntime.dll to the exe's folder. The issues is caused by having a onnxruntime.dll at "C:\Windows\WinSxS\wow64_microsoft-windows-ai-machinelearning_31bf3856ad364e35_10.0.22621.1_none_7056cab181ea1d5c\onnxruntime.dll". it must be a very old version. It blocks use and develop ort-genai on windows machines. This need to be fixed.

I see it is also confusing work with ort-genai's python api. It used to having a onnxruntime.dll at the genai install location. Now it also uses onnxruntime.dll at onnxrutime's install location. It is hard to know which one is being used.

**Comment by baijumeswani** [comment]
Ideally, the python build script will try to add the onnxruntime dlls to the same path as the exe: https://github.com/microsoft/onnxruntime-genai/blob/53e3ac93c5e49e751308bcbe558c535555304349/build.py#L565-L567

But I think on windows, we need another <config> folder at the end. If you have bandwidth, would you consider submitting a PR for this? If not, I can get to it.

For python, we load onnxruntime from inside onnxruntime's python package. Two reasons for this:

- Minimize the onnxruntime-genai package size
- Avoid problems where users want to use both ort and ort-genai together (since only one dll can be loaded at any given time).

**Comment by baijumeswani** [comment]
Fixed in https://github.com/microsoft/onnxruntime-genai/pull/963
