### ISSUE TITLE
Does Microsoft.ML.OnnxRuntimeGenAI.Cuda (version 0.4.0) support Phi-3.5 Vision Onnx format?

### ISSUE THREAD

**Issue by MaxAkbar** [microsoft/onnxruntime-genai#943]
**Describe the bug**
After migrating Phi-3.5-vision-instruct to Onnx format I am not able to use the NuGet package Microsoft.ML.OnnxRuntimeGenAI.Cuda version 0.4.0 to load the Onnx model. When referencing the folder where the Onnx model is I get an error that file not found.

```
Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: 
'Load model from C:\Users\***\source\repos\models\microsoft\Phi-3.5-vision-instruct-to-onnx\phi-3.5-v-128k-instruct-vision-onnx\ 
failed:Load model C:\Users\***\source\repos\models\microsoft\Phi-3.5-vision-instruct-to-onnx\phi-3.5-v-128k-instruct-vision-onnx\ failed. 
File doesn't exist'
```

**To Reproduce**
1. Follow [instructions](https://github.com/microsoft/Phi-3CookBook/blob/main/md/08.Update/Phi35/022.UsingORTGenAIQuantifyingPhi35.md) for converting the Phi-3.5-vision-instruct to onnx format.
2. Create a simple c# console application and load the model:
```
using Microsoft.ML.OnnxRuntimeGenAI;

string modelPath = @"C:\models\microsoft\Phi-3.5-vision-instruct-onnx";
using Model model = new Model(modelPath);
```
3. After running the application you will get an error `Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException`
4. See error in description above.

**Expected behavior**
The expected behavior is to have the model loaded and be able to run inference.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 
 - Build: Version 10.0.26120 Build 26120
 - Browser Edge

**Additional context**
I have converted the [Phi-3.5-mini-instruct](https://huggingface.co/microsoft/Phi-3.5-mini-instruct) to [Phi-3.5-mini-instruct-cuda-fp32-onnx](https://huggingface.co/Maximum2000/Phi-3.5-mini-instruct-cuda-fp32-onnx) and able to run it without any issues.

**Comment by kunal-vaishnavi** [comment]
The Phi-3 vision and Phi-3.5 vision models are split into three separate ONNX models: a vision component, an embedding component, and a text component. The `build.py` file in the instructions you linked should create all three components for you.

According to your error, the vision component cannot be found. Can you check your `modelPath` folder to see if you have any subfolders named `vision_init_export`, `vision_after_export`, or `vision_after_opt`? It's possible that something failed during the export --> optimize --> quantize process for creating the vision component. If the process failed at any point, then the latest vision component is temporarily saved in one of those subfolders before it is finally saved in `modelPath`. You may need to delete the `modelPath` folder and then re-run the `build.py` file with the latest ONNX Runtime version installed so that the process does not fail.

Please note that [re-designed ONNX models](https://github.com/microsoft/onnxruntime-genai/issues/685#issuecomment-2368927895) for Phi-3 vision and Phi-3.5 vision will be published to enable multi-image support.

**Comment by natke** [comment]
Hi @MaxAkbar, did you check your model directory for the files that Kunal described above?

**Comment by MaxAkbar** [comment]
Hi guys,

Yes I am able to see the files see image attached:

![image](https://github.com/user-attachments/assets/464e3935-5813-49ff-b987-91e1b78fefac)

In the code I reference the folder not the onnx files and I get the error file not found. If I reference the actual onnx file in this case the vision then it tries to map the config json files to the name rather the parent folder.
```
Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException
  HResult=0x80131500
  Message=Error opening C:\Users\***\source\repos\models\microsoft\Phi-3.5-vision-instruct-to-onnx\phi-3.5-v-128k-instruct-vision\phi-3.5-v-128k-instruct-vision.onnx\genai_config.json
  Source=Microsoft.ML.OnnxRuntimeGenAI
  StackTrace:
   at Microsoft.ML.OnnxRuntimeGenAI.Result.VerifySuccess(IntPtr nativeResult)
   at Microsoft.ML.OnnxRuntimeGenAI.Model..ctor(String modelPath)
   at Program.<<Main>$>g__Run|0_0() in C:\Users\***\source\repos\models\Phi35Vision\Program.cs:line 13
   at Program.<Main>$(String[] args) in C:\Users\***\source\repos\models\Phi35Vision\Program.cs:line 7
```

**Comment by MaxAkbar** [comment]
I just noticed that the file sizes are way too small, so something failed during the conversion :(. Has anyone been able to convert the vision into onnx format?

**Comment by natke** [comment]
Thank you @MaxAkbar, would you be able to attach the output from the `build.py` script here, so that we can parse for errors?

**Comment by kunal-vaishnavi** [comment]
The new [Phi-3 vision](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx) and [Phi-3.5 vision](https://huggingface.co/microsoft/Phi-3.5-vision-instruct-onnx) ONNX models have now been released. The new models support no-image, single-image, and multi-image scenarios.
