### ISSUE TITLE
Extra Options use_qdq flags work incorrectly

### ISSUE THREAD

**Issue by aendk** [microsoft/onnxruntime-genai#986]
**Describe the bug**
When building a model, 
`--extra_options use_qdq=1` and `--extra_options use_qdq=0` yield the same binary model.onnx (compared using `diff`)
which differs from the `model.onnx` when ommiting --extra_options` entirely.

**To Reproduce**
1.  Build a downloaded model:
```
$ python builder.py -m $DOWNLOADED_MODEL -e cuda -p int4 -o $SAVE_TO1 --extra_options use_qdq=1
$ python builder.py -m $DOWNLOADED_MODEL -e cuda -p int4 -o $SAVE_TO0 --extra_options use_qdq=0
$ python builder.py -m $DOWNLOADED_MODEL -e cuda -p int4 -o $SAVE_TO2
```
2. `diff` it
```
$ diff $SAVE_TO0/model.onnx $SAVE_TO1/model.onnx 
[no output, as model files are identical] 
$ diff $SAVE_TO1 $SAVE_TO2
Binary files $SAVE_TO1/model.onnx and $SAVE_TO2/model.onnx differ
```

**Expected behavior**
`use_qdq=0` should yield identical results to omitting `--extra_options use_qdq` entirely. Only `--extra_options use_qdq=1` should differ.

Please note that a setting `use_qdq` to some value is required.
 
 - OS: ubuntu24.04

**Comment by kunal-vaishnavi** [comment]
Because `use_qdq` is a setting in the `extra_options`, it is optional by default. Since a user has to manually provide `use_qdq` in the `extra_options` to use the option, this indicates that a user wants an ONNX model in the QDQ format when `use_qdq` is specified. If a user does not specify `use_qdq` in the `extra_options`, then it is understood that the QDQ format is not desired.

Thus, the model builder just checks if `use_qdq` is in `extra_options`. The specific value is not as important since there can be many variations (e.g. `use_qdq=1`, `use_qdq=true`, `use_qdq=True`, etc), and users don't always pass the right values.

**Comment by aendk** [comment]
ok, I agree and think this is not an issue right now.
However it might become one once `qdq` is more mainstream and moved out of the extra-options.
